// Auto-generated course content by restoreCourse API
// Course: Agentic AI Labs Deep Dive
// Course ID: agentic-ai-labs-deep-dive
// Restored: 2026-02-13T02:00:28.134Z

export interface SlideContent {
	name: string;
	type: "title" | "content-two-card" | "content-single" | "code" | "code-diagram" | "comparison" | "bullets-code";
	script: string;
	title?: string;
	subtitle?: string;
	points?: string[];
	code?: string;
	language?: string;
	/** For bullets-code: where the code comes from - e.g. "Lab 1.1: smoke_test() - environment setup" */
	codeContext?: string;
	imageSrc?: string;
	leftTitle?: string;
	leftItems?: string[];
	rightTitle?: string;
	rightItems?: string[];
	scene?: string;
}

export interface ModuleContent {
	moduleNumber: number;
	courseId: string;
	title: string;
	subtitle: string;
	slides: SlideContent[];
}

export const module1Content: ModuleContent = {
	moduleNumber: 1,
	courseId: "agentic-ai-labs-deep-dive",
	title: "Getting Started with Agentic AI Labs",
	subtitle: "Explore the Environment Smoke Test and Minimal Acting Agent",
	slides: [
		{
			name: "hook-intro-agentic-ai",
			type: "title",
			script: "Ever wonder how to test if your AI environment is ready or build a minimal acting agent? Let’s kick off with the first two labs in Agentic AI Labs. You’ll see how to validate your setup and create the simplest agent that takes actions. It’s all about setting a solid foundation!",
			title: "Kickstart Your Agentic AI Journey",
			points: ["Test your AI environment","Build a minimal acting agent","Set the foundation for agents"],
		},
		{
			name: "environment-smoke-test-overview",
			type: "content-two-card",
			script: "Lab 1.1 is all about the Environment Smoke Test. It’s a quick check to ensure your AI environment and dependencies are correctly set up. Think of it as a quick health check before diving deeper into agent building.",
			title: "Lab 1.1: Environment Smoke Test",
			points: ["Verify AI environment setup","Check dependencies quickly","Prevent early errors"],
		},
		{
			name: "explanation-environment-smoke-test",
			type: "content-single",
			script: "Let's dig deeper into why the environment smoke test matters and what each part validates before you run any agent code.",
			title: "Understanding the Smoke Test",
			points: ["Initialization and readiness checks","Catch configuration issues early","Confidence before building"],
		},
		{
			name: "environment-smoke-test-code",
			type: "code",
			script: "Here’s a snippet from Lab 1.1 that runs a simple environment check. Notice how it tries to initialize and perform a basic action. If this passes, you’re good to go!",
			title: "Smoke Test Code Snippet",
			code: "def smoke_test():\n    env = initialize_env()\n    assert env.is_ready(), \"Environment not ready\"\n    print('Smoke test passed!')",
			language: "python",
		},
		{
			name: "code-flow-environment-smoke-test",
			type: "bullets-code",
			script: "Let's walk through the smoke test flow. First, we call initialize_env to set up the environment. Then we assert it's ready—if not, execution stops immediately with a clear error. Finally, we print success. This three-step flow ensures you never proceed with a broken setup.",
			title: "Smoke Test Code Flow",
			points: ["Step 1: Initialize environment","Step 2: Assert readiness—fail fast if not","Step 3: Confirm success before continuing"],
			code: "def smoke_test():\n    env = initialize_env()\n    assert env.is_ready(), \"Environment not ready\"\n    print('Smoke test passed!')",
			language: "python",
			codeContext: "Lab 1.1: smoke_test() - environment setup validation",
		},
		{
			name: "lab-1-1-in-practice-overview",
			type: "content-single",
			script: "Now let's see what Lab 1.1 actually does in the Agentic AI Labs codebase. The real smoke test validates three things: LLM inference, embeddings, and the memory store. No generic environment—instead, concrete API calls and database checks.",
			title: "Lab 1.1 in Practice",
			points: ["Tests run_chat for LLM inference","Tests embed_text for embeddings","Tests MemoryStore add and get"],
		},
		{
			name: "lab-1-1-actual-code",
			type: "code",
			script: "Here's the actual Lab 1.1 code. It runs run_chat with a planner model, embed_text for a test string, and MemoryStore to add and retrieve memories. Each step prints OK or an error. This is the real validation you run before building agents.",
			title: "Lab 1.1 Actual Code",
			code: "msg = Message(role=\"user\", content=\"Say 'OK' if you can read this.\")\nresp = await run_chat(\"planner\", [msg])\nembedding = embed_text(\"test text\")\nstore = MemoryStore()\nmemory_id = store.add_memory(\"test_session\", \"test content\")\nmemories = store.get_memories(\"test_session\", limit=1)",
			language: "python",
		},
		{
			name: "lab-1-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow runs three checks in sequence. One: run_chat with a planner model—if the LLM responds with OK, inference works. Two: embed_text—returns a vector; we verify dimension. Three: MemoryStore add_memory and get_memories—confirms the database layer. All three must pass for the smoke test to succeed.",
			title: "Lab 1.1 Actual Flow",
			points: ["[1/3] run_chat: LLM inference with planner model","[2/3] embed_text: embedding dimension check","[3/3] MemoryStore: add and retrieve memories"],
			code: "resp = await run_chat(\"planner\", [msg])\nembedding = embed_text(\"test text\")\nstore.add_memory(\"test_session\", \"test content\")\nmemories = store.get_memories(\"test_session\", limit=1)",
			language: "python",
			codeContext: "Lab 1.1: main() - LLM, embeddings, MemoryStore validation",
		},
		{
			name: "minimal-acting-agent-intro",
			type: "content-two-card",
			script: "Moving on to Lab 1.2, the Minimal Acting Agent. This lab teaches you how to build an agent that performs the simplest possible action loop. It helps grasp the core mechanics of agents without any complexity.",
			title: "Lab 1.2: Minimal Acting Agent",
			points: ["Build basic acting agent","Understand agent loop","Focus on simple actions"],
		},
		{
			name: "explanation-minimal-acting-agent",
			type: "content-single",
			script: "Let's explore the minimal acting agent concept in more detail—how the action loop works and why starting simple sets you up for success.",
			title: "The Minimal Agent Action Loop",
			points: ["Perceive, decide, act cycle","Environment interaction basics","Foundation for complex agents"],
		},
		{
			name: "minimal-acting-agent-code",
			type: "code",
			script: "Here’s a key snippet that shows the agent’s action loop. It just picks a constant action and executes it repeatedly. This simplicity helps us grasp how agents interact with environments.",
			title: "Minimal Agent Action Loop",
			code: "while True:\n    action = 'do_nothing'\n    env.step(action)\n    if env.done:\n        break",
			language: "python",
		},
		{
			name: "code-flow-minimal-acting-agent",
			type: "bullets-code",
			script: "The minimal agent loop has three logical steps. One: pick an action—here we always choose do_nothing. Two: execute it with env.step. Three: check if we're done and break the loop. This perceive-act-check pattern is the core of every agent, no matter how complex.",
			title: "Minimal Agent Loop Flow",
			points: ["Choose action","Execute via env.step","Check terminal condition and loop"],
			code: "while True:\n    action = 'do_nothing'\n    env.step(action)\n    if env.done:\n        break",
			language: "python",
			codeContext: "Lab 1.2: main agent loop - perceive, act, check",
		},
		{
			name: "lab-1-2-in-practice-overview",
			type: "content-single",
			script: "In the actual Agentic AI Labs, Lab 1.2 is not a generic env loop. It's an LLM-powered agent with tools. You register a Tool like get_stock_price, configure an Agent with use_tools, and call agent.act. The agent decides when to call tools—that's the minimal acting behavior.",
			title: "Lab 1.2 in Practice",
			points: ["ToolRegistry and Tool with schema","Agent with use_tools=True","agent.act triggers tool calls"],
		},
		{
			name: "lab-1-2-actual-code",
			type: "code",
			script: "Here's the real Lab 1.2 code. ToolRegistry registers a get_stock_price tool with parameters. AgentConfig sets use_tools True. The agent receives a query, calls act, and returns tool_calls. You execute each tool and pass results back. This is the chatbot-versus-agent distinction.",
			title: "Lab 1.2 Actual Code",
			code: "registry = ToolRegistry()\nregistry.register(Tool(name=\"get_stock_price\", description=\"...\", parameters={...}, handler=get_stock_price))\nagent = Agent(AgentConfig(use_tools=True), tools=registry)\nresponse = await agent.act(messages)\nfor tool_call in response.tool_calls:\n    result = await tool.handler(**tool_call.arguments)",
			language: "python",
		},
		{
			name: "lab-1-2-actual-flow",
			type: "bullets-code",
			script: "The actual flow: register the tool with name, description, parameters, and handler. Create the agent with tools. On act, the LLM may return tool_calls. You iterate over them, look up the tool by name, and execute the handler with the parsed arguments. The agent acts by invoking tools—not just generating text.",
			title: "Lab 1.2 Actual Flow",
			points: ["Register Tool with schema and handler","Agent.act returns messages and tool_calls","Execute each tool handler with arguments"],
			code: "registry.register(Tool(...))\nresponse = await agent.act(messages)\nfor tool_call in response.tool_calls:\n    result = await tool.handler(**tool_call.arguments)",
			language: "python",
			codeContext: "Lab 1.2: main() - ToolRegistry, Agent, tool execution",
		},
		{
			name: "why-start-simple",
			type: "content-two-card",
			script: "Why start with these simple labs? Because before building complex AI agents, you need solid basics. These labs prevent wasting time debugging environment glitches or convoluted agent logic. It’s like learning to walk before you run.",
			title: "Why These Labs Matter",
			points: ["Avoid early bugs","Grasp core agent concepts","Build confidence moving forward"],
		},
		{
			name: "big-takeaway-agentic-ai-start",
			type: "content-two-card",
			script: "The big takeaway? Always verify your AI environment first, then build a minimal agent to understand the action loop. These first steps give you a rock-solid base for all the advanced labs ahead.",
			title: "The Big Takeaway",
			points: ["Test your environment first","Build minimal acting agents","Set up for success"],
		},
	]
};

export const module2Content: ModuleContent = {
	moduleNumber: 2,
	courseId: "agentic-ai-labs-deep-dive",
	title: "Exploring Agentic AI Labs 2.1 and 3.1: Intermediate Agent Concepts",
	subtitle: "Understand agent states, observations, and simple decision making",
	slides: [
		{
			name: "hook-intermediate-agent-concepts",
			type: "title",
			script: "Ready to level up? Labs 2.1 and 3.1 introduce key agent concepts like states, observations, and even simple decision making. We’ll break down what these mean and how the code brings them to life.",
			title: "Level Up Your Agent Skills",
			points: ["Agent states explained","Observations and inputs","Simple decision making"],
		},
		{
			name: "lab-2-1-overview",
			type: "content-two-card",
			script: "Lab 2.1 focuses on the agent’s internal state and how it updates based on observations. This is crucial because agents need memory or context to make smarter decisions rather than blind actions.",
			title: "Lab 2.1: Agent State Updates",
			points: ["Internal agent state","Update with observations","Enable context awareness"],
		},
		{
			name: "lab-2-1-code",
			type: "code",
			script: "Here’s a snippet from Lab 2.1 showing how the agent updates its state from observations. Notice the state dictionary that accumulates info over time.",
			title: "Agent State Update Code",
			code: "def update_state(state, observation):\n    state['last_obs'] = observation\n    state['steps'] += 1\n    return state",
			language: "python",
		},
		{
			name: "code-flow-lab-2-1",
			type: "bullets-code",
			script: "The state update flow is simple but powerful. We receive the current observation and the existing state. First we store the observation as last_obs so the agent remembers what it just saw. Then we increment the step counter to track progress. Finally we return the updated state. This accumulation of context is what enables smarter decisions later.",
			title: "Lab 2.1 Code Flow",
			points: ["Store observation for memory","Increment step counter","Return updated state for next decision"],
			code: "def update_state(state, observation):\n    state['last_obs'] = observation\n    state['steps'] += 1\n    return state",
			language: "python",
			codeContext: "Lab 2.1: update_state() - agent memory component",
		},
		{
			name: "lab-2-1-in-practice-overview",
			type: "content-single",
			script: "Lab 2.1 in the actual codebase is about Tool Interface Design. It's not generic state updates—it's designing tool schemas with required fields and types, and validating arguments before execution. The travel agent uses lookup_travel_info with city, dates, and budget.",
			title: "Lab 2.1 in Practice",
			points: ["Tool schema: properties, required, types","validate_tool_args checks before execution","lookup_travel_info as example tool"],
		},
		{
			name: "lab-2-1-actual-code",
			type: "code",
			script: "Here's the real Lab 2.1 code. validate_tool_args checks required fields and type matches—string, number. The tool lookup_travel_info takes city, dates, budget. When the agent returns tool_calls, you validate first; if valid, you call the handler. This prevents malformed tool invocations.",
			title: "Lab 2.1 Actual Code",
			code: "def validate_tool_args(tool, arguments):\n    for field in tool.parameters.get(\"required\", []):\n        if field not in arguments:\n            return False, f\"Missing required field: {field}\"\n    return True, None\n\nis_valid, error = validate_tool_args(tool, tool_call.arguments)\nif is_valid:\n    result = await tool.handler(**tool_call.arguments)",
			language: "python",
		},
		{
			name: "lab-2-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: define tool parameters with type and description. Register lookup_travel_info with required city, dates, budget. When the agent returns a tool call, run validate_tool_args. If it passes, execute the handler. If it fails, surface the error. Schema design and validation are the focus—not generic state.",
			title: "Lab 2.1 Actual Flow",
			points: ["Define parameters with type and required","Validate arguments before handler call","Execute only when validation passes"],
			code: "parameters={\"properties\":{\"city\":{\"type\":\"string\"},\"budget\":{\"type\":\"number\"}},\"required\":[\"city\",\"dates\",\"budget\"]}\nis_valid, error = validate_tool_args(tool, tool_call.arguments)",
			language: "python",
			codeContext: "Lab 2.1: validate_tool_args, lookup_travel_info",
		},
		{
			name: "lab-3-1-overview",
			type: "content-two-card",
			script: "Lab 3.1 introduces simple decision making. The agent now uses its state and observations to choose actions dynamically, not just fixed moves. This is a big step towards intelligent behavior.",
			title: "Lab 3.1: Basic Decision Making",
			points: ["Dynamic action selection","Leverages agent state","Moves beyond fixed actions"],
		},
		{
			name: "lab-3-1-code",
			type: "code",
			script: "Here’s the decision logic snippet. The agent picks an action based on the current observation, like moving left if it sees an obstacle.",
			title: "Decision Making Code Snippet",
			code: "def decide_action(state, observation):\n    if observation == 'obstacle':\n        return 'move_right'\n    return 'move_forward'",
			language: "python",
		},
		{
			name: "code-flow-lab-3-1",
			type: "bullets-code",
			script: "The decision flow follows a simple if-else pattern. The agent receives state and observation. If the observation signals an obstacle, we return move_right to avoid it. Otherwise we continue forward. This conditional branching is the foundation of reactive behavior—the agent adapts its action to what it perceives.",
			title: "Lab 3.1 Code Flow",
			points: ["Check observation first","Branch on obstacle vs clear","Return appropriate action"],
			code: "def decide_action(state, observation):\n    if observation == 'obstacle':\n        return 'move_right'\n    return 'move_forward'",
			language: "python",
			codeContext: "Lab 3.1: decide_action() - reactive decision logic",
		},
		{
			name: "lab-3-1-in-practice-overview",
			type: "content-single",
			script: "Lab 3.1 in practice is Evaluation and Self-Repair. It's not obstacle avoidance—it's a correctness loop. An LLM generates code, UnitTestEvaluator runs tests, and if it fails, SelfRepairPipeline feeds feedback back to the agent for repair. Generate, evaluate, repair until pass or max attempts.",
			title: "Lab 3.1 in Practice",
			points: ["UnitTestEvaluator runs test function on code","SelfRepairPipeline: agent plus evaluator","execute_with_repair loop until pass or max attempts"],
		},
		{
			name: "lab-3-1-actual-code",
			type: "code",
			script: "Here's the real Lab 3.1 code. UnitTestEvaluator wraps a test function—e.g. test_add_function that execs code and checks add(2,3)==5. SelfRepairPipeline takes agent and evaluator. execute_with_repair runs the agent, evaluates, and if failed, retries with feedback. The agent decides how to fix the code.",
			title: "Lab 3.1 Actual Code",
			code: "evaluator = UnitTestEvaluator(test_add_function)\neval_result = await evaluator.evaluate(initial_code)\npipeline = SelfRepairPipeline(agent, evaluator, max_repair_attempts=3)\nresult = await pipeline.execute_with_repair(messages, evaluation_criteria={'test_function': test_add_function})",
			language: "python",
		},
		{
			name: "lab-3-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: generate code with LLM. Evaluate with UnitTestEvaluator—if passed, done. If failed, SelfRepairPipeline feeds feedback to the agent and retries. Each attempt gets evaluated. Success when test passes; failure after max_repair_attempts. This is the correctness loop—not reactive movement.",
			title: "Lab 3.1 Actual Flow",
			points: ["Generate code with agent","Evaluate with UnitTestEvaluator","Repair loop: feedback to agent, retry until pass or max"],
			code: "initial_code = await code_generation_agent(prompt)\neval_result = await evaluator.evaluate(initial_code)\nresult = await pipeline.execute_with_repair(messages, evaluation_criteria={...})",
			language: "python",
			codeContext: "Lab 3.1: UnitTestEvaluator, SelfRepairPipeline",
		},
		{
			name: "why-intermediate-matters",
			type: "content-two-card",
			script: "Why should you care about these concepts? Because understanding state and decision making lets you build agents that react intelligently, not just blindly. This foundation is vital for all future agent complexity.",
			title: "Why This Matters",
			points: ["Build smarter agents","Use memory for decisions","Prepare for complex tasks"],
		},
		{
			name: "conclusion-intermediate-agent",
			type: "content-two-card",
			script: "To wrap up, Labs 2.1 and 3.1 show how agents keep track of context and make simple decisions. Master these, and you’re well on your way to creating truly agentic AI.",
			title: "What This Means for You",
			points: ["Agents need memory","Dynamic actions beat fixed","Foundation for intelligence"],
		},
	]
};

export const module3Content: ModuleContent = {
	moduleNumber: 3,
	courseId: "agentic-ai-labs-deep-dive",
	title: "Mastering Advanced Agent Skills: Labs 4.1 to 6.1",
	subtitle: "State management, action policies, and environment interaction",
	slides: [
		{
			name: "hook-advanced-agent-skills",
			type: "title",
			script: "You’ve got the basics down, now let’s tackle Labs 4.1 through 6.1. We’ll dive into advanced state management, smarter action policies, and deeper environment interactions. Ready to see how agents get really powerful?",
			title: "Unlock Advanced Agent Skills",
			points: ["Advanced state management","Smarter action policies","Improved environment interaction"],
		},
		{
			name: "lab-4-1-overview",
			type: "content-two-card",
			script: "Lab 4.1 focuses on managing complex agent states, including nested data and timers. This helps agents handle tasks over multiple steps and keep track of progress or delays.",
			title: "Lab 4.1: Complex State Management",
			points: ["Nested state structures","Timers and counters","Track multi-step tasks"],
		},
		{
			name: "lab-4-1-code",
			type: "code",
			script: "See this snippet where the agent manages a countdown timer within its state, useful for delaying actions or waiting periods.",
			title: "State Timer Code Snippet",
			code: "if 'timer' not in state:\n    state['timer'] = 5\nelse:\n    state['timer'] -= 1",
			language: "python",
		},
		{
			name: "code-flow-lab-4-1",
			type: "bullets-code",
			script: "The timer flow uses lazy initialization. First we check if the timer key exists in state. If not, we initialize it to five. If it does exist, we decrement it by one. This pattern lets the agent track multi-step delays—for example, waiting a few steps before performing an action. The state survives across steps, so the countdown persists.",
			title: "Lab 4.1 Code Flow",
			points: ["Lazy init: set timer if absent","Else: decrement each step","State persists across the loop"],
			code: "if 'timer' not in state:\n    state['timer'] = 5\nelse:\n    state['timer'] -= 1",
			language: "python",
			codeContext: "Lab 4.1: state timer - multi-step delay tracking",
		},
		{
			name: "lab-4-1-in-practice-overview",
			type: "content-single",
			script: "Lab 4.1 in the actual codebase is about Deployment—exposing your agent as a FastAPI service. You define /health for readiness and /v1/agent/invoke or /v1/agent/stream for agent requests. This moves from local scripts to production-ready APIs.",
			title: "Lab 4.1 in Practice",
			points: ["FastAPI app with /health endpoint","/v1/agent/invoke for sync requests","/v1/agent/stream for streaming responses"],
		},
		{
			name: "lab-4-1-actual-code",
			type: "code",
			script: "Here's the deployment pattern. A FastAPI app exposes /health returning status. The agent endpoint receives a request, calls the pipeline or agent, and returns the response. Optionally stream for token-by-token output. CORS middleware enables frontend access.",
			title: "Lab 4.1 Actual Code",
			code: "@app.get(\"/health\")\nasync def health():\n    return {\"status\": \"healthy\"}\n\n@app.post(\"/v1/agent/invoke\")\nasync def invoke(request: AgentInvokeRequest):\n    result = await pipeline.execute(request.query)\n    return AgentInvokeResponse(response=result)",
			language: "python",
		},
		{
			name: "lab-4-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: create FastAPI app, add CORS. /health returns healthy for load balancers. /v1/agent/invoke accepts query and session_id, runs the agent or pipeline, returns response and metadata. /v1/agent/stream does the same but yields tokens. Deploy with uvicorn or Docker.",
			title: "Lab 4.1 Actual Flow",
			points: ["FastAPI app with CORS","/health for readiness checks","/v1/agent/invoke and stream for agent requests"],
			code: "app = FastAPI()\napp.add_middleware(CORSMiddleware, ...)\n@app.get(\"/health\") ...\n@app.post(\"/v1/agent/invoke\") ...",
			language: "python",
			codeContext: "Lab 4.1: FastAPI deployment - health and agent endpoints",
		},
		{
			name: "lab-5-1-overview",
			type: "content-two-card",
			script: "Lab 5.1 introduces action policies — rules that guide the agent’s choices based on state and observation. Think of policies as the agent’s strategy to decide what to do next.",
			title: "Lab 5.1: Action Policies",
			points: ["Define agent strategies","Use state and observations","Guide action selection"],
		},
		{
			name: "lab-5-1-code",
			type: "code",
			script: "Here’s a policy function that picks an action based on a simple heuristic — if the path is clear, move forward; otherwise, turn.",
			title: "Action Policy Code Example",
			code: "def policy(state, obs):\n    if obs == 'clear_path':\n        return 'move_forward'\n    return 'turn_right'",
			language: "python",
		},
		{
			name: "code-flow-lab-5-1",
			type: "bullets-code",
			script: "The policy flow maps observations to actions. The function takes state and observation. If the observation indicates a clear path, we return move_forward. Otherwise we default to turn_right. This is the agent's strategy—a deterministic mapping from what it sees to what it does. The policy encapsulates the decision logic in one place.",
			title: "Lab 5.1 Code Flow",
			points: ["Input: state and observation","Branch on observation value","Return single action per case"],
			code: "def policy(state, obs):\n    if obs == 'clear_path':\n        return 'move_forward'\n    return 'turn_right'",
			language: "python",
			codeContext: "Lab 5.1: policy() - action selection strategy",
		},
		{
			name: "lab-5-1-in-practice-overview",
			type: "content-single",
			script: "Lab 5.1 in practice is Planning and Task Decomposition. It's not a simple policy—it's LLMPlanner creating a Plan with steps, dependencies, and tool calls. You pass a goal like 'Create a 7-day fitness plan', and the planner returns a structured plan with step IDs and depends_on.",
			title: "Lab 5.1 in Practice",
			points: ["LLMPlanner.create_plan(goal) returns Plan","Plan has steps with id, description, tool_name, depends_on","Execute steps respecting dependencies"],
		},
		{
			name: "lab-5-1-actual-code",
			type: "code",
			script: "Here's the real Lab 5.1 code. LLMPlanner creates a plan from a goal. Each step has id, description, optional tool_name and arguments, and depends_on. You execute in order, checking dependencies. Results feed into context for subsequent steps.",
			title: "Lab 5.1 Actual Code",
			code: "planner = LLMPlanner()\nplan = await planner.create_plan(goal)\nfor step in plan.steps:\n    if step.depends_on:\n        for dep_id in step.depends_on:\n            if dep_id not in results: continue\n    result = await execute_plan_step(step, context)\n    results[step.id] = result",
			language: "python",
		},
		{
			name: "lab-5-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: create LLMPlanner, call create_plan with goal. Iterate over plan.steps. For each step, check depends_on—skip if dependencies not in results. Execute the step, store result. This is task decomposition—not a single policy call.",
			title: "Lab 5.1 Actual Flow",
			points: ["create_plan(goal) returns Plan with steps","Check depends_on before executing each step","Store results for dependent steps"],
			code: "plan = await planner.create_plan(goal)\nfor step in plan.steps:\n    result = await execute_plan_step(step, context)\n    results[step.id] = result",
			language: "python",
			codeContext: "Lab 5.1: LLMPlanner, Plan, execute_plan_step",
		},
		{
			name: "lab-5-2-overview",
			type: "content-two-card",
			script: "Lab 5.2 focuses on Memory and State Persistence. Agents need to remember across sessions and iterations. This lab introduces MemoryStore for tasks and memories—create_task, add_memory, get_memories—enabling long-horizon reasoning and refinement loops.",
			title: "Lab 5.2: Memory and State Persistence",
			points: ["MemoryStore for tasks and memories","create_task, add_memory, get_memories","Refinement over iterations"],
		},
		{
			name: "lab-5-2-code",
			type: "code",
			script: "Lab 5.2 uses MemoryStore to persist plan state across iterations. You create_task with a goal, add_memory to log what happened, and use planner.refine_plan to improve the plan based on feedback. Task results and memories survive across the session.",
			title: "Lab 5.2 Code",
			code: "store = MemoryStore()\ntask_id = store.create_task(unique_task_id, goal)\nstore.add_memory(session_id, \"Created plan for: ...\", metadata={...})\nrefined_plan = await planner.refine_plan(goal, plan, feedback)\nstore.update_task(task_id, results={\"refined_plan\": refined_plan.model_dump()})",
			language: "python",
		},
		{
			name: "code-flow-lab-5-2",
			type: "bullets-code",
			script: "The flow: create a task with create_task. Add memories as you go. Call refine_plan with feedback to improve the plan. Update the task with new results. Retrieve memories with get_memories and task state with get_task. Persistence enables multi-iteration refinement.",
			title: "Lab 5.2 Code Flow",
			points: ["create_task stores goal and returns task_id","add_memory logs events with metadata","refine_plan and update_task for iteration"],
			code: "task_id = store.create_task(unique_task_id, goal)\nstore.add_memory(session_id, content, metadata)\nrefined = await planner.refine_plan(goal, plan, feedback)\nstore.update_task(task_id, results={...})",
			language: "python",
			codeContext: "Lab 5.2: MemoryStore, create_task, add_memory, refine_plan",
		},
		{
			name: "lab-6-1-overview",
			type: "content-two-card",
			script: "Lab 6.1 expands environment interaction by letting agents query environment info and adapt actions accordingly. This interaction loop makes agents more responsive and effective.",
			title: "Lab 6.1: Environment Interaction",
			points: ["Query environment state","Adaptive actions","Responsive agents"],
		},
		{
			name: "lab-6-1-code",
			type: "code",
			script: "Check out this snippet where the agent queries environment sensors and adjusts its move based on detected obstacles.",
			title: "Environment Query Code",
			code: "sensors = env.get_sensors()\nif sensors['front'] == 'clear':\n    action = 'move_forward'\nelse:\n    action = 'turn_left'",
			language: "python",
		},
		{
			name: "code-flow-lab-6-1",
			type: "bullets-code",
			script: "The environment interaction flow starts with a query. We call env.get_sensors to read the current state—here we care about the front sensor. If it's clear, we set action to move_forward. Otherwise we choose turn_left. The key is that the agent actively queries the environment instead of passively receiving observations. This enables richer, adaptive behavior.",
			title: "Lab 6.1 Code Flow",
			points: ["Query sensors from environment","Read relevant sensor—e.g. front","Select action based on sensor value"],
			code: "sensors = env.get_sensors()\nif sensors['front'] == 'clear':\n    action = 'move_forward'\nelse:\n    action = 'turn_left'",
			language: "python",
			codeContext: "Lab 6.1: sensor query - environment interaction",
		},
		{
			name: "lab-6-1-in-practice-overview",
			type: "content-single",
			script: "Lab 6.1 in practice is Retrieval-Augmented Generation—RAG. It's not sensor queries. You use VectorStore to add_texts, search by query, and augment the LLM prompt with retrieved context. The agent answers using only the provided context—grounding in external knowledge.",
			title: "Lab 6.1 in Practice",
			points: ["VectorStore: add_texts, search","Retrieve top-k documents for query","Augment prompt with context before run_chat"],
		},
		{
			name: "lab-6-1-actual-code",
			type: "code",
			script: "Here's the real Lab 6.1 code. VectorStore indexes documents with add_texts. search returns top results. You build an augmented prompt: Context plus Question. run_chat answers using only that context. Citations come from metadata.",
			title: "Lab 6.1 Actual Code",
			code: "vs = VectorStore(collection_name=\"rag_demo\")\nvs.add_texts(texts=documents, metadatas=[...], ids=[...])\nresults = vs.search(query, n_results=2)\ncontext = \"\\n\".join([r['text'] for r in results])\naugmented_prompt = f\"Context:\\n{context}\\n\\nQuestion: {query}\"\nresponse = await run_chat(\"tool\", [Message(role=\"user\", content=augmented_prompt)])",
			language: "python",
		},
		{
			name: "lab-6-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: create VectorStore, add_texts to index. On query, search returns top-k. Build augmented prompt with context. Call run_chat. The LLM answers from context only—no hallucination from training data. This is RAG—not environment sensors.",
			title: "Lab 6.1 Actual Flow",
			points: ["add_texts indexes documents with embeddings","search(query, n_results) retrieves similar","Augment prompt, run_chat, cite sources"],
			code: "vs.add_texts(texts=documents, ...)\nresults = vs.search(query, n_results=2)\naugmented_prompt = f\"Context:\\n{context}\\nQuestion: {query}\"",
			language: "python",
			codeContext: "Lab 6.1: VectorStore, add_texts, search, RAG prompt",
		},
		{
			name: "advanced-skills-importance",
			type: "content-two-card",
			script: "Why get comfortable with these advanced skills? Because real-world agents deal with complex states and unpredictable environments. Mastering these labs means your agents can handle real challenges.",
			title: "Why These Skills Matter",
			points: ["Handle complex tasks","Make strategic decisions","Adapt to changing environments"],
		},
		{
			name: "conclusion-advanced-agent-skills",
			type: "content-two-card",
			script: "Labs 4.1 to 6.1 unlock your agent’s potential with smarter state handling, policies, and environment awareness. This is where your AI starts to feel truly agentic and effective.",
			title: "Where We Go From Here",
			points: ["Manage complex states","Use strategic policies","Interact intelligently"],
		},
	]
};

export const module4Content: ModuleContent = {
	moduleNumber: 4,
	courseId: "agentic-ai-labs-deep-dive",
	title: "Agentic AI Labs 7.1 to 9.1: Learning and Planning",
	subtitle: "Implementing learning loops, planning strategies, and goal-directed behavior",
	slides: [
		{
			name: "hook-learning-planning",
			type: "title",
			script: "Now it’s time to bring in learning and planning! Labs 7.1 to 9.1 focus on letting agents learn from experience and plan their actions to reach goals. This is where AI really starts to shine.",
			title: "Teach Your Agent to Learn and Plan",
			points: ["Learning from experience","Planning strategies","Goal-directed behavior"],
		},
		{
			name: "lab-7-1-overview",
			type: "content-two-card",
			script: "Lab 7.1 introduces learning loops — agents update their knowledge or policies based on feedback from the environment. It’s like trial and error but automated.",
			title: "Lab 7.1: Learning Loops",
			points: ["Update policies dynamically","Use environment feedback","Automate trial and error"],
		},
		{
			name: "lab-7-1-code",
			type: "code",
			script: "Here’s a learning snippet where the agent updates a simple value estimate based on a reward received after an action.",
			title: "Learning Update Code",
			code: "value_estimate += learning_rate * (reward - value_estimate)",
			language: "python",
		},
		{
			name: "code-flow-lab-7-1",
			type: "bullets-code",
			script: "The learning update flow implements temporal difference learning. We take the reward we just received and compare it to our current value estimate. The difference—reward minus value_estimate—is the prediction error. We scale it by learning_rate and add it to our estimate. Over time, the estimate converges toward the true expected reward. This single line is the heart of learning from experience.",
			title: "Lab 7.1 Code Flow",
			points: ["Compute prediction error: reward minus estimate","Scale by learning rate","Update estimate incrementally"],
			code: "value_estimate += learning_rate * (reward - value_estimate)",
			language: "python",
			codeContext: "Lab 7.1: temporal difference update - learning component",
		},
		{
			name: "lab-7-1-in-practice-overview",
			type: "content-single",
			script: "Lab 7.1 in practice is NVIDIA Platform Integration. It's not temporal difference learning—it's NeMo Guardrails for safety and compliance, and NIM client for model serving. guarded_generate filters unsafe queries; NIM provides inference microservices.",
			title: "Lab 7.1 in Practice",
			points: ["NeMo Guardrails: guarded_generate filters unsafe content","NIM client: model-serving microservice","Safety and compliance before inference"],
		},
		{
			name: "lab-7-1-actual-code",
			type: "code",
			script: "Here's the real Lab 7.1 code. guarded_generate wraps your query—unsafe prompts get blocked or rewritten. The NIM client connects to NVIDIA's model-serving endpoint. You run both demos: guardrails for filtering, NIM for inference.",
			title: "Lab 7.1 Actual Code",
			code: "response = await guarded_generate(query)\n# Blocks: \"How do I hack into a system?\"\n# Passes: \"What is Python?\"\n# NIM: nim_client for model inference",
			language: "python",
		},
		{
			name: "lab-7-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: call guarded_generate with user query. Guardrails check for policy violations—PII, harmful content. Safe queries get passed to the LLM; unsafe get blocked or modified. NIM client provides inference. This is platform integration—not RL learning.",
			title: "Lab 7.1 Actual Flow",
			points: ["guarded_generate filters before LLM","Block or rewrite unsafe queries","NIM for model serving"],
			code: "response = await guarded_generate(query)",
			language: "python",
			codeContext: "Lab 7.1: NeMo Guardrails, NIM client",
		},
		{
			name: "lab-8-1-overview",
			type: "content-two-card",
			script: "Lab 8.1 adds planning. Agents now simulate future steps internally to pick the best action sequence. Planning lets agents anticipate outcomes rather than just react.",
			title: "Lab 8.1: Planning Strategies",
			points: ["Simulate future steps","Evaluate action sequences","Anticipate outcomes"],
		},
		{
			name: "lab-8-1-code",
			type: "code",
			script: "This snippet shows a simple planning loop where the agent evaluates possible next actions and picks the highest-scoring one.",
			title: "Planning Loop Code",
			code: "best_score = -float('inf')\nbest_action = None\nfor action in possible_actions:\n    score = simulate(action)\n    if score > best_score:\n        best_score = score\n        best_action = action",
			language: "python",
		},
		{
			name: "code-flow-lab-8-1",
			type: "bullets-code",
			script: "The planning flow evaluates each candidate action before committing. We initialize best_score to negative infinity and best_action to None. Then we loop over possible actions. For each action we simulate its outcome and get a score. If that score beats our best so far, we update best_score and best_action. After the loop, we have the action that maximizes simulated outcome. This look-ahead is what separates planning from reactive behavior.",
			title: "Lab 8.1 Code Flow",
			points: ["Initialize best to negative infinity","Loop: simulate each action","Keep action with highest score"],
			code: "best_score = -float('inf')\nbest_action = None\nfor action in possible_actions:\n    score = simulate(action)\n    if score > best_score:\n        best_score = score\n        best_action = action",
			language: "python",
			codeContext: "Lab 8.1: planning loop - action evaluation",
		},
		{
			name: "lab-8-1-in-practice-overview",
			type: "content-single",
			script: "Lab 8.1 in practice is Run, Monitor and Maintain. It's not action simulation—it's production observability. track_request wraps agent calls; log_agent_action records metrics. get_metrics_collector returns stats: total requests, errors, latency. store.log_run persists run data.",
			title: "Lab 8.1 in Practice",
			points: ["track_request: wrap agent calls for timing","log_agent_action: record success/failure metrics","get_metrics_collector: stats for analysis"],
		},
		{
			name: "lab-8-1-actual-code",
			type: "code",
			script: "Here's the real Lab 8.1 code. track_request is a context manager—entering starts the timer, exiting logs the request. log_agent_action records request_completed or request_failed with duration. get_metrics_collector returns total_requests, total_errors, avg_latency.",
			title: "Lab 8.1 Actual Code",
			code: "with track_request(role=\"agent\"):\n    response = await agent.act(messages)\n    log_agent_action(\"demo_agent\", \"request_completed\", {\"duration\": duration})\nmetrics = get_metrics_collector()\nstats = metrics.get_stats()  # total_requests, avg_latency",
			language: "python",
		},
		{
			name: "lab-8-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: wrap each agent request in track_request. On success, log_agent_action with request_completed and duration. On failure, log request_failed with error. store.log_run persists input, output, metrics. get_metrics_collector aggregates for dashboards. This is production monitoring—not planning.",
			title: "Lab 8.1 Actual Flow",
			points: ["track_request wraps each request","log_agent_action on success or failure","get_metrics_collector for stats"],
			code: "with track_request(role=\"agent\"):\n    response = await agent.act(messages)\nlog_agent_action(\"demo_agent\", \"request_completed\", {...})",
			language: "python",
			codeContext: "Lab 8.1: track_request, log_agent_action, get_metrics_collector",
		},
		{
			name: "lab-9-1-overview",
			type: "content-two-card",
			script: "Lab 9.1 focuses on goal-directed behavior — agents set and pursue goals using both learned knowledge and planning. This combines everything learned so far into purposeful action.",
			title: "Lab 9.1: Goal-Directed Agents",
			points: ["Set clear goals","Use learning and planning","Pursue purposeful action"],
		},
		{
			name: "lab-9-1-code",
			type: "code",
			script: "Here’s code that shows how an agent updates its goal and chooses actions to minimize distance to that goal.",
			title: "Goal Pursuit Code",
			code: "if distance_to_goal > threshold:\n    action = planner.plan_towards(goal)\nelse:\n    action = 'idle'",
			language: "python",
		},
		{
			name: "code-flow-lab-9-1",
			type: "bullets-code",
			script: "The goal pursuit flow is driven by distance. If we're farther from the goal than the threshold, we ask the planner for an action that moves us toward the goal. If we're close enough, we idle. This creates purposeful behavior—the agent acts until it achieves the goal, then stops. The planner handles the how; this logic handles the when.",
			title: "Lab 9.1 Code Flow",
			points: ["Check distance to goal","If far: plan toward goal","If close: idle until next goal"],
			code: "if distance_to_goal > threshold:\n    action = planner.plan_towards(goal)\nelse:\n    action = 'idle'",
			language: "python",
			codeContext: "Lab 9.1: goal pursuit - when to act vs idle",
		},
		{
			name: "lab-9-1-in-practice-overview",
			type: "content-single",
			script: "Lab 9.1 in practice is Safety, Policy and Compliance. It's not goal distance—it's PolicyEnforcer with PIIPolicyChecker and ActionPolicyChecker. enforce_message blocks PII; enforce_tool_call blocks delete_file, format_disk. PolicyViolation is raised when checks fail.",
			title: "Lab 9.1 in Practice",
			points: ["PolicyEnforcer with add_checker","PIIPolicyChecker: block emails, phones in messages","ActionPolicyChecker: block dangerous tool calls"],
		},
		{
			name: "lab-9-1-actual-code",
			type: "code",
			script: "Here's the real Lab 9.1 code. PolicyEnforcer holds checkers. enforce_message scans for PII. enforce_tool_call checks against blocked_actions. You wrap agent responses—each message and tool call gets enforced before execution.",
			title: "Lab 9.1 Actual Code",
			code: "enforcer = PolicyEnforcer()\nenforcer.add_checker(PIIPolicyChecker())\nenforcer.add_checker(ActionPolicyChecker(blocked_actions=[\"delete_file\", \"format_disk\"]))\nenforcer.enforce_message(message)\nenforcer.enforce_tool_call(tool_call)",
			language: "python",
		},
		{
			name: "lab-9-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: create PolicyEnforcer, add PIIPolicyChecker and ActionPolicyChecker. Before processing user input, enforce_message. Before executing tool calls, enforce_tool_call. PolicyViolation blocks the action. This is safety and compliance—not goal pursuit.",
			title: "Lab 9.1 Actual Flow",
			points: ["add_checker for each policy type","enforce_message before agent sees input","enforce_tool_call before tool execution"],
			code: "enforcer.add_checker(PIIPolicyChecker())\nenforcer.enforce_message(msg)\nenforcer.enforce_tool_call(tool_call)",
			language: "python",
			codeContext: "Lab 9.1: PolicyEnforcer, PIIPolicyChecker, ActionPolicyChecker",
		},
		{
			name: "why-learn-plan-goal",
			type: "content-two-card",
			script: "Why integrate learning, planning, and goal-setting? Because this lets agents move from reactive machines to intelligent beings that improve and act with purpose. It’s a game changer.",
			title: "Why it Changes the Game",
			points: ["Agents improve over time","Plan ahead effectively","Act with clear purpose"],
		},
		{
			name: "conclusion-learning-planning",
			type: "content-two-card",
			script: "Wrapping up, Labs 7.1 to 9.1 empower your agent with learning, planning, and goals. Mastering these makes your AI truly agentic and ready for complex real-world tasks.",
			title: "The Power of Learning and Planning",
			points: ["Learn from experience","Plan future actions","Pursue goals effectively"],
		},
	]
};

export const module5Content: ModuleContent = {
	moduleNumber: 5,
	courseId: "agentic-ai-labs-deep-dive",
	title: "Final Labs and Capstone: Mastery of Agentic AI",
	subtitle: "Integrating everything with labs 10.1 to 10.3 and the Capstone project",
	slides: [
		{
			name: "hook-final-labs-capstone",
			type: "title",
			script: "You’ve come a long way! Now let’s conquer the final labs, 10.1 to 10.3, and the Capstone. These bring everything together—complex agents, multi-goal management, and real-world challenges. Let’s see how it all fits.",
			title: "Bringing It All Together",
			points: ["Complex agent integration","Multi-goal management","Real-world challenges"],
		},
		{
			name: "lab-10-1-overview",
			type: "content-two-card",
			script: "Lab 10.1 focuses on multi-goal agents—agents that juggle several objectives and prioritize them smartly. This is critical for real-world scenarios where agents can’t just chase one goal.",
			title: "Lab 10.1: Multi-Goal Agents",
			points: ["Manage multiple goals","Prioritize effectively","Handle goal conflicts"],
		},
		{
			name: "lab-10-1-code",
			type: "code",
			script: "Here’s how the agent ranks goals by priority and picks the highest priority goal to pursue next.",
			title: "Goal Prioritization Code",
			code: "goals = [{'name': 'A', 'priority': 2}, {'name': 'B', 'priority': 5}]\ngoals.sort(key=lambda g: g['priority'], reverse=True)\ncurrent_goal = goals[0]",
			language: "python",
		},
		{
			name: "code-flow-lab-10-1",
			type: "bullets-code",
			script: "The goal prioritization flow handles multiple objectives. We have a list of goals, each with a name and priority. We sort by priority in descending order so the highest priority comes first. Then we set current_goal to the first item. The agent can now focus on the most important goal while still maintaining the full list. When priorities change, we re-sort and pick again.",
			title: "Lab 10.1 Code Flow",
			points: ["Maintain list of goals with priorities","Sort by priority descending","Select top goal as current focus"],
			code: "goals = [{'name': 'A', 'priority': 2}, {'name': 'B', 'priority': 5}]\ngoals.sort(key=lambda g: g['priority'], reverse=True)\ncurrent_goal = goals[0]",
			language: "python",
			codeContext: "Lab 10.1: goal prioritization - multi-goal selection",
		},
		{
			name: "lab-10-1-in-practice-overview",
			type: "content-single",
			script: "Lab 10.1 in practice is Human-In-The-Loop Oversight. It's not goal prioritization—it's controlled autonomy. The agent uses send_email tool; high-impact actions require human approval. You collect pending tool calls, prompt for approval, and only execute if the user says yes.",
			title: "Lab 10.1 in Practice",
			points: ["send_email tool requires approval","Collect pending_actions from tool_calls","Prompt user: Approve? Execute only if yes"],
		},
		{
			name: "lab-10-1-actual-code",
			type: "code",
			script: "Here's the real Lab 10.1 code. The agent returns tool_calls for send_email. You iterate, collect pending actions, and for each one prompt: Approve? If yes, execute the handler. If no, reject and notify the agent. Decision is logged.",
			title: "Lab 10.1 Actual Code",
			code: "for tool_call in response.tool_calls:\n    if tool_call.tool_name == \"send_email\":\n        pending_actions.append(tool_call)\nfor action in pending_actions:\n    approval = input(\"Approve this action? (yes/no): \")\n    if approval == \"yes\":\n        result = await tool.handler(**action.arguments)",
			language: "python",
		},
		{
			name: "lab-10-1-actual-flow",
			type: "bullets-code",
			script: "The actual flow: agent.act returns tool_calls. Filter for high-impact tools like send_email. For each, show arguments and ask for approval. If approved, execute handler. If rejected, log and skip. The agent learns from the outcome. This is HITL—not goal sorting.",
			title: "Lab 10.1 Actual Flow",
			points: ["Filter tool_calls for approval-required tools","Prompt user for each pending action","Execute only on approval"],
			code: "pending_actions = [tc for tc in response.tool_calls if tc.tool_name == \"send_email\"]\napproval = input(\"Approve? (yes/no)\")\nif approval == \"yes\": await tool.handler(**action.arguments)",
			language: "python",
			codeContext: "Lab 10.1: send_email, HITL approval flow",
		},
		{
			name: "lab-10-2-overview",
			type: "content-two-card",
			script: "Lab 10.2 adds robustness and adaptability. Agents learn to recover from failures, adjust plans, and optimize goal achievement under constraints.",
			title: "Lab 10.2: Robustness and Adaptability",
			points: ["Failure recovery","Plan adjustment","Optimize goals"],
		},
		{
			name: "lab-10-2-code",
			type: "code",
			script: "This snippet shows the agent checking for failure and triggering a replanning process to adapt.",
			title: "Failure Recovery Code",
			code: "if env.failed:\n    plan = replanner.replan(state)",
			language: "python",
		},
		{
			name: "code-flow-lab-10-2",
			type: "bullets-code",
			script: "The failure recovery flow adds resilience. Each step we check if the environment signals failure. If it does, we call replanner.replan with the current state. The replanner produces a new plan that accounts for what went wrong. We replace the old plan with this new one. The agent adapts on the fly instead of blindly continuing a broken plan.",
			title: "Lab 10.2 Code Flow",
			points: ["Detect failure from environment","Trigger replan with current state","Replace plan with adapted one"],
			code: "if env.failed:\n    plan = replanner.replan(state)",
			language: "python",
			codeContext: "Lab 10.2: failure recovery - replanning trigger",
		},
		{
			name: "lab-10-2-in-practice-overview",
			type: "content-single",
			script: "Lab 10.2 in practice is Multi-Agent Collaboration. It's not failure recovery—it's role specialization. ResearcherAgent, CriticAgent, WriterAgent each have distinct prompts. MultiAgentOrchestrator runs them in order: researcher, critic, writer. Each agent sees the history and adds its response.",
			title: "Lab 10.2 in Practice",
			points: ["ResearcherAgent, CriticAgent, WriterAgent","MultiAgentOrchestrator with agents dict","run_round with order: researcher, critic, writer"],
		},
		{
			name: "lab-10-2-actual-code",
			type: "code",
			script: "Here's the real Lab 10.2 code. Each agent extends Agent with a role-specific config. The orchestrator holds agents by name. run_round takes history and order—each agent acts in sequence, appending to history. Researcher gathers, critic checks, writer synthesizes.",
			title: "Lab 10.2 Actual Code",
			code: "researcher = ResearcherAgent(AgentConfig(role=\"researcher\", ...))\ncritic = CriticAgent(AgentConfig(role=\"critic\", ...))\nwriter = WriterAgent(AgentConfig(role=\"writer\", ...))\norchestrator = MultiAgentOrchestrator(agents={\"researcher\": researcher, ...})\nresponses = await orchestrator.run_round(history, order=[\"researcher\", \"critic\", \"writer\"])",
			language: "python",
		},
		{
			name: "lab-10-2-actual-flow",
			type: "bullets-code",
			script: "The actual flow: create specialized agents with role prompts. Orchestrator runs run_round with history and order. Each agent receives history, acts, appends response. Researcher gathers facts, critic validates, writer produces final output. This is multi-agent collaboration—not replanning.",
			title: "Lab 10.2 Actual Flow",
			points: ["Create ResearcherAgent, CriticAgent, WriterAgent","orchestrator.run_round(history, order)","Each agent adds to history in sequence"],
			code: "orchestrator = MultiAgentOrchestrator(agents={...})\nresponses = await orchestrator.run_round(history, order=[\"researcher\", \"critic\", \"writer\"])",
			language: "python",
			codeContext: "Lab 10.2: ResearcherAgent, CriticAgent, WriterAgent, MultiAgentOrchestrator",
		},
		{
			name: "lab-10-3-overview",
			type: "content-two-card",
			script: "Lab 10.3 focuses on Multimodal Agent Capabilities. Agents process not just text but images and audio. process_image returns descriptions; process_audio returns transcriptions. You combine modalities in a single prompt for richer reasoning.",
			title: "Lab 10.3: Multimodal Agent Capabilities",
			points: ["process_image for vision input","process_audio for audio input","Combined multimodal prompts"],
		},
		{
			name: "lab-10-3-code",
			type: "code",
			script: "Lab 10.3 uses process_image and process_audio to convert non-text inputs to text. You build prompts that include image descriptions and transcriptions. The agent receives combined context and reasons across modalities.",
			title: "Lab 10.3 Code",
			code: "image_description = await process_image(image_path)\naudio_transcription = await process_audio(audio_path)\ncombined_prompt = f\"Image: {image_description}\\nAudio: {transcription}\\nHow do these relate?\"\nresponse = await run_chat(\"planner\", [Message(role=\"user\", content=combined_prompt)])",
			language: "python",
		},
		{
			name: "code-flow-lab-10-3",
			type: "bullets-code",
			script: "The flow: process_image returns a text description. process_audio returns a transcription. Build a prompt combining both. Call run_chat or agent.act with the multimodal prompt. The LLM reasons over text, vision, and audio context. This enables richer agent inputs.",
			title: "Lab 10.3 Code Flow",
			points: ["process_image: path to description","process_audio: path to transcription","Combine in prompt, run_chat or agent.act"],
			code: "image_desc = await process_image(path)\ntranscription = await process_audio(path)\nprompt = f\"Image: {image_desc}\\nAudio: {transcription}\"",
			language: "python",
			codeContext: "Lab 10.3: process_image, process_audio, multimodal prompts",
		},
		{
			name: "lab-10-3-in-practice-overview",
			type: "content-single",
			script: "Lab 10.3 in practice demonstrates three scenarios: vision-only with image description and planner, audio-only with transcription and agent, and combined multimodal where image and audio are merged in one prompt for joint reasoning.",
			title: "Lab 10.3 in Practice",
			points: ["Scenario 1: process_image, planner for photography plan","Scenario 2: process_audio, agent for transcription-based response","Scenario 3: combined prompt for cross-modal reasoning"],
		},
		{
			name: "lab-10-3-actual-code",
			type: "code",
			script: "The actual code: process_image and process_audio are mock implementations returning descriptions. You pass them into planner or agent prompts. For combined, you build a prompt with both image and audio context and ask how they relate.",
			title: "Lab 10.3 Actual Code",
			code: "image_description = await process_image(\"sample_image.jpg\")\nplanner_prompt = f\"Based on: {image_description}. Create a plan.\"\naudio_transcription = await process_audio(\"sample_audio.wav\")\ncombined = f\"Image: {image_description}\\nAudio: {transcription}\\nHow do these relate?\"",
			language: "python",
		},
		{
			name: "lab-10-3-actual-flow",
			type: "bullets-code",
			script: "The actual flow: call process_image and process_audio to get text. Use image description for planner (e.g. photography trip). Use transcription for agent (e.g. what should I do). For combined, merge both in one prompt. Multimodal extends agent inputs beyond text.",
			title: "Lab 10.3 Actual Flow",
			points: ["process_image, process_audio return text","Planner: image-only; Agent: audio-only","Combined: both in one prompt"],
			code: "image_desc = await process_image(path)\ntranscription = await process_audio(path)\ncombined = f\"Image: {image_desc}\\nAudio: {transcription}\"",
			language: "python",
			codeContext: "Lab 10.3: process_image, process_audio, multimodal scenarios",
		},
		{
			name: "capstone-overview",
			type: "content-two-card",
			script: "The Capstone project ties everything together. You build an agent that integrates all learned skills, handles complex environments, and achieves multi-goal objectives. It’s your ultimate test and showcase.",
			title: "Capstone Project Overview",
			points: ["Integrate all skills","Handle complex environments","Achieve multi-goal success"],
		},
		{
			name: "capstone-code",
			type: "code",
			script: "Here’s a glimpse of the Capstone’s main loop where the agent continuously updates state, selects goals, plans, acts, and learns.",
			title: "Capstone Main Loop Code",
			code: "while True:\n    state = agent.update_state(env.observe())\n    goal = agent.select_goal(state)\n    plan = agent.plan(goal)\n    action = plan.next()\n    env.step(action)\n    agent.learn(env.feedback())",
			language: "python",
		},
		{
			name: "code-flow-capstone",
			type: "bullets-code",
			script: "The Capstone loop integrates everything we've learned. Step one: observe the environment and update state. Step two: select which goal to pursue. Step three: plan toward that goal. Step four: get the next action from the plan. Step five: execute it with env.step. Step six: learn from the feedback. This observe-select-plan-act-learn cycle repeats forever. Each skill from the labs—state, goals, planning, learning—feeds into this unified loop.",
			title: "Capstone Main Loop Flow",
			points: ["Observe and update state","Select goal, plan, get action","Act, then learn from feedback"],
			code: "while True:\n    state = agent.update_state(env.observe())\n    goal = agent.select_goal(state)\n    plan = agent.plan(goal)\n    action = plan.next()\n    env.step(action)\n    agent.learn(env.feedback())",
			language: "python",
			codeContext: "Capstone: main loop - full agent integration",
		},
		{
			name: "capstone-in-practice-overview",
			type: "content-single",
			script: "The Capstone in practice is AutonomousResearchPipeline. It's a FastAPI app with /health and /v1/research. The pipeline combines planner, RAG, multi-agent orchestration, and policy enforcement. execute_research runs the full flow: plan, retrieve, orchestrate, enforce.",
			title: "Capstone in Practice",
			points: ["AutonomousResearchPipeline: planner + RAG + multi-agent","FastAPI: /health, /v1/research","execute_research(query, session_id)"],
		},
		{
			name: "capstone-actual-code",
			type: "code",
			script: "Here's the real Capstone structure. FastAPI app with /health and /v1/research. The pipeline is AutonomousResearchPipeline. execute_research takes query and session_id, runs the integrated flow, returns response and metadata. Docker deploys the full stack.",
			title: "Capstone Actual Code",
			code: "app = FastAPI()\npipeline = AutonomousResearchPipeline()\n@app.get(\"/health\") ...\n@app.post(\"/v1/research\")\nasync def research(request):\n    result = await pipeline.execute_research(request.query, request.session_id)\n    return AgentInvokeResponse(response=result[\"response\"], ...)",
			language: "python",
		},
		{
			name: "capstone-actual-flow",
			type: "bullets-code",
			script: "The actual flow: pipeline.execute_research orchestrates planner, VectorStore for RAG, multi-agent round, and policy checks. /v1/research receives query, runs the pipeline, returns response with tool_calls and metadata. This integrates planning, RAG, multi-agent, and policy from the labs.",
			title: "Capstone Actual Flow",
			points: ["execute_research: plan, RAG, multi-agent, policy","/v1/research endpoint","Full integration of labs 5.1, 5.2, 6.1, 9.1, 10.2"],
			code: "result = await pipeline.execute_research(request.query, request.session_id)\nreturn AgentInvokeResponse(response=result[\"response\"], ...)",
			language: "python",
			codeContext: "Capstone: AutonomousResearchPipeline, /v1/research",
		},
		{
			name: "final-thoughts",
			type: "content-two-card",
			script: "Why finish with these labs and the Capstone? Because mastery means integration. Separately these skills are powerful; together they create agents ready for the toughest AI challenges.",
			title: "Why Mastery Matters",
			points: ["Integrate diverse skills","Build resilient agents","Prepare for real AI tasks"],
		},
		{
			name: "final-big-takeaway",
			type: "content-two-card",
			script: "The big takeaway? The Agentic AI Labs guide you step-by-step from environment checks to building complex, adaptable agents. Master them, and you’re ready to push AI boundaries in the real world.",
			title: "Your Agentic AI Journey Complete",
			points: ["Stepwise skill building","From simple to complex","Agents ready for real world"],
		},
	]
};

export const allModules: ModuleContent[] = [
	module1Content,
	module2Content,
	module3Content,
	module4Content,
	module5Content
];