import React from "react";
import { Sequence, useVideoConfig, Audio, staticFile } from "remotion";
import { TitleSlide } from "../components/TitleSlide";
import { ContentSlide } from "../components/ContentSlide";
import { AnimatedContentSlide } from "../components/AnimatedContentSlide";
import { ComparisonSlide } from "../components/ComparisonSlide";
import { AnimatedComparisonSlide } from "../components/AnimatedComparisonSlide";
import { CodeSlide } from "../components/CodeSlide";
import { AnimatedCodeSlide } from "../components/AnimatedCodeSlide";
import { TransitionSlide } from "../components/TransitionSlide";
import { CrossFadeWrapper } from "../components/CrossFadeWrapper";
import { getAudioDuration, calculateSlideDuration } from "../utils/audioDuration";

export const Module1: React.FC = () => {
	const { fps } = useVideoConfig();
	const crossFadeDuration = 0.3; // 0.3 second cross-fade overlap for smoother transitions
	const whooshDuration = 0.57; // Whoosh sound duration (measured from actual file)

	// Audio file paths (generated by scripts/generateAudio.ts)
	// Use staticFile to properly reference files from the public directory
	const audioFiles = {
		title: staticFile("audio/module1-title.wav"),
		whyIaC: staticFile("audio/module1-whyIaC.wav"),
		comparison: staticFile("audio/module1-comparison.wav"),
		workflow: staticFile("audio/module1-workflow.wav"),
		initCode: staticFile("audio/module1-initCode.wav"),
		whyTypeScript: staticFile("audio/module1-whyTypeScript.wav"),
		typescriptCode: staticFile("audio/module1-typescriptCode.wav"),
		summary: staticFile("audio/module1-summary.wav"),
		whoosh: staticFile("audio/whoosh.wav"),
	};

	// Get actual audio durations from measured files (no hardcoded fallbacks)
	// Run: npm run measure-actual-audio to update these values
	const audioDurations = {
		title: getAudioDuration("module1-title"),
		whyIaC: getAudioDuration("module1-whyIaC"),
		comparison: getAudioDuration("module1-comparison"),
		workflow: getAudioDuration("module1-workflow"),
		initCode: getAudioDuration("module1-initCode"),
		whyTypeScript: getAudioDuration("module1-whyTypeScript"),
		typescriptCode: getAudioDuration("module1-typescriptCode"),
		summary: getAudioDuration("module1-summary"),
	};

	let currentFrame = 0;

	// Helper to add a slide - voice determines slide length exactly
	// Pattern: audio plays fully, then whoosh, then next slide (no gap)
	const addSlide = (audioDuration: number, isLast: boolean = false) => {
		// Slide duration = audio duration exactly (voice determines length, no extra time)
		const slideDuration = audioDuration;
		const start = currentFrame;
		
		// Calculate when next slide should start
		// Current slide: audioDuration (exact)
		// Whoosh: 0.3 seconds
		// Next slide starts after: audioDuration + whooshDuration
		if (!isLast) {
			currentFrame += (slideDuration + whooshDuration) * fps;
		} else {
			// Last slide: just audio, no transition
			currentFrame += slideDuration * fps;
		}
		
		// Sequence duration = audio duration exactly (no cross-fade added to audio time)
		// Cross-fade only affects visual transition, not audio playback
		return { start, duration: slideDuration * fps, slideDuration, audioDuration };
	};

	// Calculate all slide timings based on actual audio durations
	const titleSlide = addSlide(audioDurations.title);
	const whyIaCSlide = addSlide(audioDurations.whyIaC);
	const comparisonSlide = addSlide(audioDurations.comparison);
	const workflowSlide = addSlide(audioDurations.workflow);
	const initCodeSlide = addSlide(audioDurations.initCode);
	const typescriptSlide = addSlide(audioDurations.whyTypeScript);
	const typescriptCodeSlide = addSlide(audioDurations.typescriptCode);
	const summarySlide = addSlide(audioDurations.summary, true); // Last slide, no transition

	// Total duration is the final currentFrame position (in frames)
	// This is what we'll use to calculate the Composition duration
	const totalDurationInFrames = currentFrame;
	const totalDurationInSeconds = totalDurationInFrames / fps;

	return (
		<div
			style={{
				width: "100%",
				height: "100%",
				background: "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)",
				position: "relative",
			}}
		>
			{/* Title Slide */}
			<Sequence
				from={titleSlide.start}
				durationInFrames={titleSlide.audioDuration * fps}
			>
				<Audio src={audioFiles.title} />
				<CrossFadeWrapper
					totalDuration={titleSlide.audioDuration}
					fadeInDuration={0.5}
					fadeOutDuration={0}
				>
					<TitleSlide
						title="AWS Infrastructure as Code with Pulumi"
						subtitle="Module 1: Pulumi and IaC Fundamentals"
					/>
				</CrossFadeWrapper>
			</Sequence>

			{/* Whoosh transition sound - plays after audio finishes */}
			<Sequence
				from={titleSlide.start + titleSlide.audioDuration * fps}
				durationInFrames={whooshDuration * fps}
			>
				<Audio src={audioFiles.whoosh} startFrom={0} />
			</Sequence>

			{/* Why IaC Slide - Starts after whoosh */}
			<Sequence
				from={whyIaCSlide.start}
				durationInFrames={whyIaCSlide.audioDuration * fps}
			>
				<Audio src={audioFiles.whyIaC} />
				<CrossFadeWrapper
					totalDuration={whyIaCSlide.audioDuration}
					fadeInDuration={crossFadeDuration}
					fadeOutDuration={crossFadeDuration}
				>
					<AnimatedContentSlide
						title="Why Infrastructure as Code?"
						points={[
							"Repeatable and consistent deployments",
							"Version control for infrastructure changes",
							"Automated provisioning and teardown",
							"Reduced human error and faster recovery",
							"Documentation as executable code",
						]}
						slideName="whyIaC"
					/>
				</CrossFadeWrapper>
			</Sequence>

			{/* Whoosh transition sound */}
			<Sequence
				from={whyIaCSlide.start + whyIaCSlide.audioDuration * fps}
				durationInFrames={whooshDuration * fps}
			>
				<Audio src={audioFiles.whoosh} startFrom={0} />
			</Sequence>

			{/* Comparison Slide - Starts after whoosh */}
			<Sequence
				from={comparisonSlide.start}
				durationInFrames={comparisonSlide.audioDuration * fps}
			>
				<Audio src={audioFiles.comparison} />
				<CrossFadeWrapper
					totalDuration={comparisonSlide.audioDuration}
					fadeInDuration={crossFadeDuration}
					fadeOutDuration={crossFadeDuration}
				>
					<AnimatedComparisonSlide
						title="Pulumi vs Terraform & CloudFormation"
						leftTitle="Traditional IaC"
						leftItems={[
							"Domain-specific languages (HCL, YAML)",
							"Limited programming constructs",
							"Separate tooling for testing",
							"Steeper learning curve",
						]}
						rightTitle="Pulumi"
						rightItems={[
							"Real programming languages (TypeScript, Python)",
							"Full IDE support and autocomplete",
							"Native testing and validation",
							"Better developer ergonomics",
						]}
						slideName="comparison"
					/>
				</CrossFadeWrapper>
			</Sequence>

			{/* Whoosh transition sound */}
			<Sequence
				from={comparisonSlide.start + comparisonSlide.audioDuration * fps}
				durationInFrames={whooshDuration * fps}
			>
				<Audio src={audioFiles.whoosh} startFrom={0} />
			</Sequence>

			{/* Pulumi Workflow Slide - Starts after whoosh */}
			<Sequence
				from={workflowSlide.start}
				durationInFrames={workflowSlide.audioDuration * fps}
			>
				<Audio src={audioFiles.workflow} />
				<CrossFadeWrapper
					totalDuration={workflowSlide.audioDuration}
					fadeInDuration={crossFadeDuration}
					fadeOutDuration={crossFadeDuration}
				>
					<AnimatedContentSlide
						title="Pulumi Workflow Commands"
						points={[
							"pulumi init - Initialize a new project",
							"pulumi preview - See planned changes",
							"pulumi up - Deploy infrastructure",
							"pulumi destroy - Remove all resources",
							"pulumi config - Manage configuration",
						]}
						slideName="workflow"
					/>
				</CrossFadeWrapper>
			</Sequence>

			{/* Whoosh transition sound */}
			<Sequence
				from={workflowSlide.start + workflowSlide.audioDuration * fps}
				durationInFrames={whooshDuration * fps}
			>
				<Audio src={audioFiles.whoosh} startFrom={0} />
			</Sequence>

			{/* Code Example: Init - Starts after whoosh */}
			<Sequence
				from={initCodeSlide.start}
				durationInFrames={initCodeSlide.audioDuration * fps}
			>
				<Audio src={audioFiles.initCode} />
				<CrossFadeWrapper
					totalDuration={initCodeSlide.audioDuration}
					fadeInDuration={crossFadeDuration}
					fadeOutDuration={crossFadeDuration}
				>
				<AnimatedCodeSlide
					title="Initialize a Pulumi Project"
					code={`# Create a new Pulumi project
pulumi new aws-typescript

# This creates:
# - index.ts (main infrastructure code)
# - Pulumi.yaml (project metadata)
# - Pulumi.dev.yaml (stack configuration)
# - package.json (dependencies)`}
					language="bash"
					slideName="initCode"
					audioStartFrame={initCodeSlide.start}
				/>
				</CrossFadeWrapper>
			</Sequence>

			{/* Whoosh transition sound */}
			<Sequence
				from={initCodeSlide.start + initCodeSlide.audioDuration * fps}
				durationInFrames={whooshDuration * fps}
			>
				<Audio src={audioFiles.whoosh} startFrom={0} />
			</Sequence>

			{/* Why TypeScript Slide - Starts after whoosh */}
			<Sequence
				from={typescriptSlide.start}
				durationInFrames={typescriptSlide.audioDuration * fps}
			>
				<Audio src={audioFiles.whyTypeScript} />
				<CrossFadeWrapper
					totalDuration={typescriptSlide.audioDuration}
					fadeInDuration={crossFadeDuration}
					fadeOutDuration={crossFadeDuration}
				>
					<AnimatedContentSlide
						title="Why TypeScript for DevOps?"
						points={[
							"Type safety catches errors before deployment",
							"Excellent IDE autocomplete and IntelliSense",
							"Rich ecosystem of AWS SDK and libraries",
							"Familiar to many developers",
							"Easy to test and refactor",
						]}
						slideName="whyTypeScript"
					/>
				</CrossFadeWrapper>
			</Sequence>

			{/* Code Example: TypeScript - Starts after whoosh */}
			<Sequence
				from={typescriptCodeSlide.start}
				durationInFrames={typescriptCodeSlide.audioDuration * fps}
			>
				<Audio src={audioFiles.typescriptCode} />
				<CrossFadeWrapper
					totalDuration={typescriptCodeSlide.audioDuration}
					fadeInDuration={crossFadeDuration}
					fadeOutDuration={crossFadeDuration}
				>
				<AnimatedCodeSlide
					title="TypeScript Infrastructure Code"
					code={`import * as aws from "@pulumi/aws";

// Create a VPC with type safety
const vpc = new aws.ec2.Vpc("main-vpc", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
    tags: {
        Name: "main-vpc",
        Environment: "production",
    },
});

// Export the VPC ID
export const vpcId = vpc.id;

// TypeScript provides autocomplete and
// compile-time error checking`}
					language="typescript"
					slideName="typescriptCode"
					audioStartFrame={typescriptCodeSlide.start}
				/>
				</CrossFadeWrapper>
			</Sequence>

			{/* Whoosh transition sound */}
			<Sequence
				from={typescriptCodeSlide.start + typescriptCodeSlide.audioDuration * fps}
				durationInFrames={whooshDuration * fps}
			>
				<Audio src={audioFiles.whoosh} startFrom={0} />
			</Sequence>

			{/* Summary Slide - Starts after whoosh */}
			{/* Add small buffer (0.1s) to ensure audio plays fully */}
			<Sequence
				from={summarySlide.start}
				durationInFrames={(summarySlide.audioDuration + 0.1) * fps}
			>
				<Audio src={audioFiles.summary} />
				<CrossFadeWrapper
					totalDuration={summarySlide.audioDuration + 0.1}
					fadeInDuration={crossFadeDuration}
					fadeOutDuration={0}
				>
					<AnimatedContentSlide
						title="Module 1 Summary"
						points={[
							"IaC provides repeatable, version-controlled infrastructure",
							"Pulumi offers better developer experience than traditional tools",
							"TypeScript brings type safety to infrastructure code",
							"Pulumi workflow: init, preview, up, destroy, config",
							"Next: Project setup and AWS credentials",
						]}
						slideName="summary"
					/>
				</CrossFadeWrapper>
			</Sequence>
		</div>
	);
};
