// Utility to get audio duration from files
// This will be used to dynamically adjust slide durations based on actual audio length

export interface AudioInfo {
	path: string;
	duration: number; // in seconds
}

// Audio durations in seconds - measured from actual audio files
// Auto-generated by: npm run measure-actual-audio
// Last updated: 2026-01-15T06:38:33.282Z
export const audioDurations: Record<string, number> = {
	"module1-comparison": 30.08,
	"module1-initCode": 22.88,
	"module1-summary": 22.88,
	"module1-title": 31.2,
	"module1-typescriptCode": 25.12,
	"module1-whyIaC": 30.28,
	"module1-whyTypeScript": 17.48,
	"module1-workflow": 23.44,
};

/**
 * Get audio duration for a slide
 * @param audioFileName - Name of the audio file (e.g., "module1-title")
 * @returns Duration in seconds, or throws error if not found (no fallback to prevent hardcoding)
 */
export function getAudioDuration(audioFileName: string): number {
	const duration = audioDurations[audioFileName];
	if (duration === undefined) {
		throw new Error(
			`Audio duration not found for "${audioFileName}". Run: npm run measure-actual-audio`
		);
	}
	return duration;
}

/**
 * Calculate slide duration based on audio length
 * @param audioDuration - Audio duration in seconds
 * @param transitionDuration - Transition/gap duration in seconds (default: 1)
 * @returns Slide duration in seconds (audio + transition)
 */
export function calculateSlideDuration(
	audioDuration: number,
	transitionDuration: number = 1
): number {
	return audioDuration + transitionDuration;
}
