// Script to measure actual audio file durations and update audioDuration.ts
// This ensures we use real durations, not hardcoded estimates

import * as fs from "fs";
import * as path from "path";

interface AudioMeasurement {
	name: string;
	duration: number;
}

async function measureWavDuration(filePath: string): Promise<number | null> {
	return new Promise((resolve) => {
		// Use HTML5 Audio API via a simple approach
		// For Node.js, we'll parse WAV headers
		try {
			const buffer = fs.readFileSync(filePath);
			
			// Check RIFF header
			if (buffer.toString("ascii", 0, 4) !== "RIFF") {
				resolve(null);
				return;
			}
			
			// Read sample rate (offset 24)
			const sampleRate = buffer.readUInt32LE(24);
			const channels = buffer.readUInt16LE(22);
			const bitsPerSample = buffer.readUInt16LE(34);
			
			if (sampleRate === 0) {
				resolve(null);
				return;
			}
			
			// Find data chunk
			let offset = 36;
			while (offset < buffer.length - 8) {
				const chunkId = buffer.toString("ascii", offset, offset + 4);
				const chunkSize = buffer.readUInt32LE(offset + 4);
				
				if (chunkId === "data") {
					const dataSize = chunkSize;
					const bytesPerSample = bitsPerSample / 8;
					const duration = dataSize / (sampleRate * channels * bytesPerSample);
					
					if (isFinite(duration) && duration > 0 && duration < 3600) {
						resolve(Math.round(duration * 100) / 100);
						return;
					}
				}
				
				offset += 8 + chunkSize;
				if (chunkSize % 2 === 1) offset++; // Align to word boundary
			}
			
			resolve(null);
		} catch (error) {
			console.error(`Error measuring ${filePath}:`, error);
			resolve(null);
		}
	});
}

async function measureAllAudio(): Promise<AudioMeasurement[]> {
	const baseAudioDir = path.join(__dirname, "../public/audio");
	const measurements: AudioMeasurement[] = [];
	
	// Scan course subdirectories
	const entries = fs.readdirSync(baseAudioDir, { withFileTypes: true });
	
	for (const entry of entries) {
		if (entry.isDirectory()) {
			const courseId = entry.name;
			const courseDir = path.join(baseAudioDir, courseId);
			const files = fs.readdirSync(courseDir).filter((f) => f.endsWith(".wav") && f.startsWith("module") && !f.includes("whoosh"));
			
			for (const file of files) {
				const filePath = path.join(courseDir, file);
				const duration = await measureWavDuration(filePath);
				
				if (duration !== null) {
					// Use courseId/moduleName as key for course isolation
					const name = `${courseId}/${file.replace(".wav", "")}`;
					measurements.push({ name, duration });
					console.log(`  ${name}: ${duration}s`);
				} else {
					console.error(`  Failed to measure ${courseId}/${file}`);
				}
			}
		} else if (entry.isFile() && entry.name.endsWith(".wav") && entry.name.startsWith("module")) {
			// Legacy: files in root audio directory (without courseId)
			const filePath = path.join(baseAudioDir, entry.name);
			const duration = await measureWavDuration(filePath);
			
			if (duration !== null) {
				const name = entry.name.replace(".wav", "");
				measurements.push({ name, duration });
				console.log(`  ${name}: ${duration}s (legacy)`);
			} else {
				console.error(`  Failed to measure ${entry.name}`);
			}
		}
	}
	
	return measurements.sort((a, b) => a.name.localeCompare(b.name));
}

function updateAudioDurationFile(measurements: AudioMeasurement[]) {
	const filePath = path.join(__dirname, "../src/utils/audioDuration.ts");
	
	const content = `// Utility to get audio duration from files
// This will be used to dynamically adjust slide durations based on actual audio length

export interface AudioInfo {
	path: string;
	duration: number; // in seconds
}

// Audio durations in seconds - measured from actual audio files
// Auto-generated by: npm run measure-actual-audio
// Last updated: ${new Date().toISOString()}
export const audioDurations: Record<string, number> = {
${measurements.map((m) => `\t"${m.name}": ${m.duration},`).join("\n")}
};

/**
 * Get audio duration for a slide
 * @param audioFileName - Name of the audio file (e.g., "module1-title")
 * @returns Duration in seconds, or throws error if not found (no fallback to prevent hardcoding)
 */
export function getAudioDuration(audioFileName: string): number {
	const duration = audioDurations[audioFileName];
	if (duration === undefined) {
		throw new Error(
			\`Audio duration not found for "\${audioFileName}". Run: npm run measure-actual-audio\`
		);
	}
	return duration;
}

/**
 * Calculate slide duration based on audio length
 * @param audioDuration - Audio duration in seconds
 * @param transitionDuration - Transition/gap duration in seconds (default: 1)
 * @returns Slide duration in seconds (audio + transition)
 */
export function calculateSlideDuration(
	audioDuration: number,
	transitionDuration: number = 1
): number {
	return audioDuration + transitionDuration;
}
`;

	fs.writeFileSync(filePath, content, "utf-8");
	console.log(`\n✓ Updated ${filePath}`);
}

async function main() {
	console.log("Measuring actual audio file durations...\n");
	
	const measurements = await measureAllAudio();
	
	if (measurements.length === 0) {
		console.error("No audio files found or all measurements failed!");
		process.exit(1);
	}
	
	console.log(`\n✓ Measured ${measurements.length} audio files\n`);
	
	updateAudioDurationFile(measurements);
	
	console.log("\n✓ Done! Audio durations updated.");
	console.log("\nNext steps:");
	console.log("  1. Restart Remotion Studio (npm start)");
	console.log("  2. Slides will now use actual audio durations");
}

main().catch(console.error);
